### PR TITLE
Fix a bug that was preventing new windows from being tiled

### PR DESCRIPTION
**Pull request by ianyh**

### CODE REVIEW

**Comment by mwoffenden** [comment]
Good news.  How do I get a version with the fix?

**Comment by ianyh** [comment]
I'm going to put a build out today.

**Comment by mwoffenden** [comment]
Great.  Where do go to I see/download a new build?

**Comment by ianyh** [comment]
If you have the option in preferences for getting development builds you just need to check for updates via the status bar menu.

**Comment by mwoffenden** [comment]
I did that.  

Now I see: "Amethyst can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move Amethyst to your Applications folder, relaunch it from there, and try again."

But it IS in the Applications folder.  And I did launch it from there.

**Comment by mwoffenden** [comment]
Never mind - I'm using [Path Finder](https://cocoatech.com/) and found a [solution to my issue here](https://github.com/sparkle-project/Sparkle/issues/936).

**Comment by mwoffenden** [comment]
Latest beta version (0.11.3b3) tiles very nicely!

**Comment by ianyh** [comment]
Glad to hear it.

**Pull request merged**
