### PR TITLE
Custom Layouts

### LINKED ISSUE #51: User-defined layouts through an extension
Great work !
What about a config file for creating new custom layouts easily ?

Thanks

[Trello Card](https://trello.com/c/Vx9e7umC/23-amethyst-configuration-file-for-layouts)

### PR DESCRIPTION
**Pull request by ianyh**
Closes #51, #1126 

First pass implementing some custom layout behavior with layouts implemented in javascript and dropped in an Application Support directory. Went with js because JavaScriptCore is built in which made it significantly easier than implementing some kind of config.

This doesn't support everything yet, but wanted to get feedback on it if anyone wants to take a look.

- [x] Allow for dynamic layout keys
- [x] Implement basic frame generation
- [x] Implement basic state tracking
- [x] Implement state tracked through window changes
- [x] Route commands
- [x] Add commands to preferences
* ~~Pass in some subset of user configuration to frame assignments~~

### CODE REVIEW

**Comment by rraihansaputra** [comment]
Hi @ianyh, I've taken a look and tried at modifying the js layout. Currently it works great, and I know this is a WIP, but some notes from me:
- I'm a bit unsure of the default path for the js layouts. It makes sense if there will be a UI to add js files to be stored there. But as a first iteration, I think defaulting to a `~/.config/Amethyst` would be fine for now. If it works well with this, the UI can come later. What do you think?
- How are you planning to pass the user config to the JS layouts? ex: increase/decrease ratio
- JS layouts feels a bit slower on adjustment, but still acceptable for me
- EDIT: Ignore this point. After thinking about this more, I think defining the expand/shrink/increase/decrease functions on the CustomLayout class is fine. | |  I think the `CustomLayout.command()` should be exposed instead of being private. I routed `shrinkMainPane`, `expandMainPane`, `increaseMainPaneCount` and `decreaseMainPaneCount` through the `CustomLayout.command(key:)`, and defined the functions in JS command. Works well, and if the function/key doesn't exist, it's handled by CustomLayout instead of having to catch the error at the command/hotkey.
  - This also enables JS functions to have predefined command keys to implement by the layouts themselves, on top of the command1-4 keys. The command 1-4 keys is great for custom functions. 
- I think the CustomLayout needs to assert certain things, as the JS layouts can't be tested on build as the Swift Layouts. This also makes sure JS layouts won't send windows to inaccessible positions. Simple assertions should be fine (ex: x/y can't be more than screenHeight/screenWidth)

  

Thank you so much for this. I'll be daily driving this for now.

**Comment by ianyh** [comment]
The default path is `~/Library/Application Support/Amethyst/Layouts`, which is pretty idiomatic for Mac apps.

**Comment by ianyh** [comment]
For the config I probably want to pass an explicit subset in a JavaScript object. There's some stuff like floating lists that expose app usage information and I don't want to give that to arbitrary JavaScript.

And yeah, I would expect it to be a bit slower because it has to get interpreted.

**Review by cybniv — DISMISSED** [review]

**Comment by cybniv** [comment]
@ianyh I'm really sorry, I just couldn't resist in seeing what happens when I approve this PR. I shouldn't have had the rights to do so, as I never committed anything here and am not part of the Team.

Nevertheless, it was possible to do so.

I can not review other PRs in this repository, so I guess this was a GitHub bug, not a misconfiguration issue. Still good to know.

**Comment by ianyh** [comment]
Here's a notarized build if anyone wants to try it.

[Amethyst.zip](https://github.com/ianyh/Amethyst/files/8241314/Amethyst.zip)

**Comment by Bellavene** [comment]
> Here's a notarized build if anyone wants to try it.
> 
> [Amethyst.zip](https://github.com/ianyh/Amethyst/files/8241314/Amethyst.zip)

Any js examples?

**Comment by chancez** [comment]
> > Here's a notarized build if anyone wants to try it.
> > [Amethyst.zip](https://github.com/ianyh/Amethyst/files/8241314/Amethyst.zip)
> 
> Any js examples?

https://github.com/ianyh/Amethyst/tree/js-layouts/AmethystTests/Model/CustomLayouts

**Comment by Bellavene** [comment]
> > > Here's a notarized build if anyone wants to try it.
> > > [Amethyst.zip](https://github.com/ianyh/Amethyst/files/8241314/Amethyst.zip)
> > 
> > 
> > Any js examples?
> 
> https://github.com/ianyh/Amethyst/tree/js-layouts/AmethystTests/Model/CustomLayouts

Thank you. Sorry for my blindness.

**Comment by Alex23rodriguez** [comment]
I'm really glad this is getting worked on :) i'd love to be able to create some Ultrawide-oriented layouts (uniform-columns.js works great for 3 windows).

I would like to point out a bug, however. When using the Uniform Columns layout, Amethyst crashes when using the "move focus counter clockwise" and "move focus clockwise" keyboard shortcuts.

**Comment by ianyh** [comment]
> I'm really glad this is getting worked on :) i'd love to be able to create some Ultrawide-oriented layouts (uniform-columns.js works great for 3 windows).
> 
> I would like to point out a bug, however. When using the Uniform Columns layout, Amethyst crashes when using the "move focus counter clockwise" and "move focus clockwise" keyboard shortcuts.

Thanks for catching that crash.

**Comment by Henkru** [comment]
The custom layout support looks awesome! I'd like to try to implement my custom 3-column middle retain [layout](https://github.com/Henkru/Amethyst/commit/b7979e3be655ad6417c3927b05c36c7e7c66b786) as a JS  layout, so I don't have to build my own version of Amethyst every time. What would be a recommended way to debug javascript code for custom layouts? I didn't notice any mention about this on the documentation.

**Pull request merged**
