### PR TITLE
Add preference to hide menu bar icon

### LINKED ISSUE #299: add option to hide icon in macOS status bar
Just a suggestion i thought of. :)

[Trello Card](https://trello.com/c/JAMAIByQ/128-amethyst-add-option-to-hide-icon-in-osx-top-bar)

### PR DESCRIPTION
**Pull request by jbernardo95**
This PR introduces a new preference that controls whether the menu bar icon is visible or not.

It requires a relaunch for the property to take effect.

SCR-20240103-pwon

Closes https://github.com/ianyh/Amethyst/issues/299

### CODE REVIEW

**Review by ianyh — CHANGES_REQUESTED** [review]
Cool! This should get added as a configuration option, though, which would also make it available from a config file.

**Comment by jbernardo95** [comment]
@ianyh done ✅

**Review by ianyh — APPROVED** [review]

**Comment by jbernardo95** [comment]
@ianyh any plans to release a new version soon?

**Comment by singhprd** [comment]
@ianyh - I've just been looking for this option, it would be great if a new version was released!

Thanks for the work on this app! ❤️ ❤️ ❤️

**Pull request merged**
