### PR TITLE
New app + main menu + menu bar icons

### PR DESCRIPTION
**Pull request by Zabriskije**
Hey Ian,

I've made a new app icon to conform with Apple's HIG used since Big Sur, and while I was there, I also modified the menu bar icon and the main menu icons (swapped with SF Symbols ones + fallbacks for macOS 11 and earlier).

I've made a build, and everything seems fine (Ventura 13.4, Xcode 14.3).

Here's a preview:

<p align="center"></p>

<p align="center"></p>

### CODE REVIEW

**Comment by ianyh** [comment]
This is awesome! Thank you! I'll give it a whirl to see how the status item icons look, but this is really cool! Much better than my hack job in gimp ten years ago.

I just did a double take typing out "ten years ago."

**Comment by Zabriskije** [comment]
So glad you like it :)

Would be fun to read a new post about those ten years in your blog 👀

**Review by ianyh — APPROVED** [review]

**Comment by scottrohrig** [comment]
This is great, how do I open the settings now?

**Comment by ianyh** [comment]
It's a different icon in the status bar.

**Comment by scottrohrig** [comment]
Sorry I should have said, I disabled the icon in the menu bar.

**Comment by ianyh** [comment]
If you launch the application when it is open, that should open settings.

**Comment by scottrohrig** [comment]
Okay, that's what I read. Thanks for the quick reply. Hmm. Looks like I have an issue with my machine then, because it doesn't do that. I'll make a config file and reset it there.

**Comment by ianyh** [comment]
It's possible I broke the behavior somehow. I can give you a terminal command to run, but probably not until the morning. You can also add a configuration file that sets that flag to false.

**Comment by ianyh** [comment]
@scottrohrig if you still need it:
```
% defaults write com.amethyst.Amethyst hide-menu-bar-icon 0
```

**Comment by scottrohrig** [comment]
Thanks, I added the config file and manually set it from there. That brought the settings window up again when launching the app and the icon showed up again. Things are all good now. Dig the new icons also.

**Pull request merged**
