### PR TITLE
Make TwoPane layout adaptive to screen orientation

### PR DESCRIPTION
**Pull request by mwz**
I've been experimenting recently with a vertical monitor setup and I decided to follow up on #1124 and made the Two Pane layout to adapt to horizontal/vertical view depending on the screen orientation (i.e. it does vertical tiling on a vertical monitor).

I've used it a lot over the last couple of days on both a horizontal and a vertical monitor - I have a keyboard shortcut to trigger it and imho It seems to be way more convenient to reuse the existing layout rather than create a separate layout, but please let me know if you'd rather have it as a separate one.

Please see a short demo below:

https://user-images.githubusercontent.com/1190768/149244106-d2cc802f-6fda-4bde-bac1-c7ab1466c315.mp4

### CODE REVIEW

**Comment by mwz** [comment]
Hi @ianyh, any chance you could take a look at this PR?
Those test failures don't seem to be related to my changes.

**Comment by ianyh** [comment]
Yeah, you need to pull in upstream. It has a fix for the tests compilation issue.

**Comment by mwz** [comment]
> Yeah, you need to pull in upstream. It has a fix for the tests compilation issue.

ok - done 👍🏻

**Comment by mwz** [comment]
hey @ianyh, any chance this can be merged if you're happy with the changes?

**Review by ianyh — APPROVED** [review]
Nice.

**Pull request merged**
