### PR TITLE
Fix Amethyst behavior with Stage Manager from MacOS Ventura 

### PR DESCRIPTION
**Pull request by Muzosh**
This PR should fix the Amethyst usage with Stage Manager, see https://github.com/ianyh/Amethyst/issues/1258#issuecomment-1293792227

### CODE REVIEW

**Review by ianyh — CHANGES_REQUESTED** [review]
This could inhibit desired behavior involving minimized windows in general. For example, a window that is minimized before Amethyst starts that is then unminimized independent of staging could be lost.

Edit: Sorry if this review was premature.

**Comment by Muzosh** [comment]
> This could inhibit desired behavior involving minimized windows in general. For example, a window that is minimized before Amethyst starts that is then unminimized independent of staging could be lost.
> 
> Edit: Sorry if this review was premature.

Well, I just tried it and it seems that my assumptions were wrong. It basically behaves the same way.
So maybe Stage Manager does not just minimize windows? I have tried to find some development documentation so we as developer can recognize, which windows are displayed and which ones are hidden by Stage Manager, but I did not find anything.

**Comment by Muzosh** [comment]
From what I was able to read from the code, the `Window:shouldBeManaged()` method is called every time windows are reevaluated in `WindowsManager:reevaluateWindows()` - this function does not run repeatedly?

**Comment by Muzosh** [comment]
So, a loooong over-due update. I have finally found time and reason to look at this again and it seems that there is no way of knowing, whether the app window is hidden in the stage manager or not.

Firstly, the only mention of Stage Manager in relation to AppKit is [here](https://developer.apple.com/videos/play/wwdc2022/10074/?time=45). As far as my understanding goes, they basically say: "Don't worry about Stage Manager, it will work as expected based on what `collectionBehavior` you choose". So this is basically AppKit->Stage Manager link, but we want to get information from StageManager to he AppKit.

I also found, that similar buried problem was discussed in [yabai](https://github.com/koekeishiya/yabai/issues?q=stage+manager), however, no solutions so far.

**Pull request closed without merging**
