### PR TITLE
Minimum width and height for active tiled window

### PR DESCRIPTION
**Pull request by axs221**
## Related issue

* #494
* #495
* Possibly affects: #651 (regarding commit 691e27a)

## Motivation

As mentioned in the related issue and its duplicates, it is helpful when 
Amethyst pushes windows off-screen at smaller sizes, and then pulls
those frames back into the window entirely when the window is focused.

However, this behavior was only performed for windows that have sizing
constraints. Additionally, it would be helpful to be able to configure the
minimum size desired when the window is focused and the behavior is
performed.

## Modifications

Configuration settings and related behavior for minimum height and width
of focused window. Minimums only apply to focused window, which helps
minimize times when tiled windows may be hidden from adjacent windows
overlapping if minimum size were applied all the time.

Also minor adjustment to fix how it is determined if frame is within window,
to prevent stuttering issues that would occur if the focus following mouse
option was selected.

## Video

https://cl.ly/2q2h3v0v0Z26

## Screenshots

image

image

[Trello Card](https://trello.com/c/oMOgvetw/291-amethyst-minimum-width-and-height-for-active-tiled-window)

### CODE REVIEW

**Comment by ianyh** [comment]
Nice. I'll try to take a more thorough look at this soon, but at first glance it looks good. It looks like the version of CocoaPods using the Gemfile is wrong, though. I'll update that in `development` so you can rebase onto it before merging this.

**Comment by axs221** [comment]
@ianyh Sounds good. I reverted the COCOAPODS version setting in the lock file and have my environment set up with 1.3.1. I left the Gemfile unmodified and I will pull it in from development as you mentioned.

**Comment by axs221** [comment]
I am not sure yet about 691e27a. While it is better for Chrome dialogs on click, it has the side effect of also making all windows of that process focus / zoom when one window is focused. It is mostly an improvement, but need to check how it works on multi-window interfaces like the GIMP, which I am assuming is one process.

**Comment by axs221** [comment]
The "Parent" attribute doesn't get me what I want unfortunately. It gets me process information with a title of the application name and windowID == 0. Comparing parents of Chrome windows is always true for all Chrome windows. I am about out of ideas for how to make dialogs work well without marking all windows of the same process as focused.

**Comment by ianyh** [comment]
The parent of the windows is probably the application element. Sheets can be attached to windows, but aren't necessarily. I don't think modal alerts are attached to anything but the application itself. Regardless, windows of an application are all going to have the same process ID, so I'm not sure the focused check there works.

Preventing window focus when there's a modal for an application seems like a generally good idea, but I would have to think more about what it would look like with multiple applications, each of which might be able to have a dialog open, etc. Either way that should be a separate change from the minimum size thing.

**Comment by axs221** [comment]
@ianyh Sounds good to me. I will revert 691e27a56be8f303a033ca5d05da68da4a50c7dc. It won't provide the best user experience until a solution to have the parent window set as focused, but at least people don't have to use this PR for now if that bothers them.

**Comment by ianyh** [comment]
Should fix https://github.com/ianyh/Amethyst/issues/17

**Comment by ianyh** [comment]
Okay. This looks good, but I'd like to try to get #627 in before merging this. I don't mind handling any merge conflicts that come up.

**Comment by ianyh** [comment]
Looks good! I think I resolved the merge conflicts correctly.

**Pull request merged**
