### PR TITLE
Window limit

### PR DESCRIPTION
**Pull request by MutatingFunc**
This adds documentation for the new autominimize feature.

### CODE REVIEW

**Review by ianyh — CHANGES_REQUESTED** [review]
Helpful docs, but I actually meant adding the preferences key to the doc on configuration.

**Comment by MutatingFunc** [comment]
Sorry for the delay, does this cover everything?

**Review by ianyh — APPROVED** [review]

**Comment by ianyh** [comment]
Yup! Thanks.

**Comment by Bellavene** [comment]
Now let's make it perfect and add an unminimizer, so windows will cycle through and restored from minimized state if a free spot has been delivered!

https://user-images.githubusercontent.com/77557804/220089867-78ce93fb-e485-457e-a9aa-ab5a8a39665f.mp4

**Pull request merged**
